### ISSUE TITLE
Calculate Forces with Parametric Bodies

### ISSUE THREAD

**Issue by fg320** [weymouth/ParametricBodies.jl#1]
Hi Gabe, thanks for the great code. My question is, would it be possible to make a `ParametricBody` compatible with the `WaterLily.∮nds `method in Waterlily/Metric.jl? So far I think they are not compatible due to `ParametricBodies` missing the `sdf `field. Thank you!

**Comment by weymouth** [comment]
Every type of `Body` needs to implement the `sdf`, not just `AutoBody`.  It's a requirement of any type that extends `Body`, ie

[measure_sdf!(a::AbstractArray,body::AbstractBody,t=0) = @inside a[I] = sdf(body,loc(0,I),t)
](https://github.com/weymouth/WaterLily.jl/blob/3caf8b03c429aaeca6f245c4016aa328c2934734/src/Body.jl#L76C1-L77C1)

For a `ParametericBody`, it's found here:
https://github.com/weymouth/ParametricBodies.jl/blob/0282eb41d8abf19ade1a1d589f31d5dd2b48a9df/src/ParametricBodies.jl#L76

**Comment by weymouth** [comment]
I'm confused by this comment. `AutoBody` doesn't have a field for the `sdf` either... what's the difference?

**Comment by fg320** [comment]
I am new to Julia, so I apologize if the notation is incorrect. 

`AutoBody.jl` has:
- `sdf` method that can be called as `body.sdf(x,t)`
- `sdf` function that can be called with `sdf(body,loc(0,I),t)`, defined as `sdf(body::AutoBody,x,t) = body.sdf(x,t)`

`ParametricBodies.jl` has:
- `sdf` function that can be called with `sdf(body,loc(0,I),t)`, defined as `sdf(body::ParametricBody,x,t) = surf_props(body,x,t)[1]`

Whilst there are two `sdf(body,loc(0,I),t)` functions, one for each `Body` type. the difference is that `ParametricBodies' does not have a `body.sdf' method, which is used in the `∮nds` function.

**Comment by weymouth** [comment]
So change the integration routine to use `sdf(body,x,t)`...

**Comment by fg320** [comment]
That's what I ended up doing. However, it would be nice to have a `body.sdf(x,t)` for `ParametricBodies` as well, as it gets called relatively often in `WaterLily`.

**Comment by weymouth** [comment]
All of those should be switched to `sdf(body,x,t)`. Function overloading is one of the core features of Julia, so we want to use that.
